# Generated by Django 6.1 on 2026-08-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('audience', models.CharField(choices=[('portal', 'پرتال (عمومی)'), ('members', 'اعضا (فقط کاربران لاگین\u200cکرده)'), ('managers', 'مدیران (فقط ادمین)')], default='portal', max_length=20, verbose_name='مخاطب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
