# Generated by Django 6.0.7 on 2026-07-30 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر ها',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام مهمان\u200cسراها')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='venues/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='venues.city', verbose_name='شهرها')),
            ],
            options={
                'verbose_name': 'مهمان سرا',
                'verbose_name_plural': 'مهمان سراها',
            },
        ),
        migrations.CreateModel(
            name='RoomUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=100, verbose_name='نوع واحد')),
                ('room_type', models.CharField(blank=True, max_length=100, verbose_name='نوع استراحتگاه')),
                ('status', models.CharField(choices=[('undefined', 'تعریف نشده'), ('available', 'ظرفیت خالی'), ('full', 'ظرفیت پر')], default='undefined', max_length=20, verbose_name='وضعیت')),
                ('price_per_night', models.PositiveBigIntegerField(verbose_name='قیمت هر شب (ریال)')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='venues.venue', verbose_name='مهمان سرا')),
            ],
            options={
                'verbose_name': 'واحد اقامتی',
                'verbose_name_plural': 'واحد های اقامتی',
            },
        ),
    ]
