# Generated by Django 6.0.7 on 2026-07-30 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('undefined', 'تعریف نشده'), ('available', 'ظرفیت خالی'), ('full', 'ظرفیت پر')], default='undefined', max_length=20, verbose_name='وضعیت')),
                ('room_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='venues.roomunit', verbose_name='واحد اقامتی')),
            ],
            options={
                'verbose_name': 'ظرفیت روزانه',
                'verbose_name_plural': 'ظرفیت\u200cهای روزانه',
                'unique_together': {('room_unit', 'date')},
            },
        ),
    ]
