# Generated by Django 6.0.7 on 2026-08-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomunit',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='room_units/', verbose_name='تصویر واحد'),
        ),
    ]
