# Generated by Django 6.0.7 on 2026-08-01 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_roomunit_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='city_slides/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='یه توضیح کوتاه')),
                ('order', models.PositiveBigIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='venues.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'اسلاید شهر',
                'verbose_name_plural': 'اسلایدهای شهر',
                'ordering': ['order'],
            },
        ),
    ]
