# Generated by Django 6.0.7 on 2026-08-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_cityslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='rules',
            field=models.TextField(blank=True, verbose_name='قوانین و مقررات'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('undefined', 'تعریف نشده'), ('available', 'ظرفیت خالی'), ('full', 'ظرفیت تکمیل')], default='undefined', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='roomunit',
            name='status',
            field=models.CharField(choices=[('undefined', 'تعریف نشده'), ('available', 'ظرفیت خالی'), ('full', 'ظرفیت تکمیل')], default='undefined', max_length=20, verbose_name='وضعیت'),
        ),
    ]
