# Generated by Django 6.0.7 on 2026-08-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_city_rules_alter_availability_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='rules',
        ),
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('undefined', 'تعریف نشده'), ('available', 'ظرفیت خالی'), ('full', 'ظرفیت پر')], default='undefined', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='roomunit',
            name='status',
            field=models.CharField(choices=[('undefined', 'تعریف نشده'), ('available', 'ظرفیت خالی'), ('full', 'ظرفیت پر')], default='undefined', max_length=20, verbose_name='وضعیت'),
        ),
    ]
