# Generated by Django 6.0.7 on 2026-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_remove_city_rules_alter_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='rules',
            field=models.TextField(blank=True, verbose_name='قوانین و مقررات'),
        ),
    ]
