# Generated by Django 6.1 on 2026-08-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_city_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='city',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='پست الکترونیک'),
        ),
        migrations.AddField(
            model_name='city',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='نمابر'),
        ),
        migrations.AddField(
            model_name='city',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدیر استراحتگاه'),
        ),
        migrations.AddField(
            model_name='city',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='تلفن'),
        ),
    ]
