# Generated by Django 6.0.7 on 2026-08-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_city_address_city_email_city_fax_city_manager_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
    ]
