# Generated by Django 6.0.7 on 2026-08-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='اعتبار عضویت'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='تصویر پروفایل'),
        ),
    ]
