# Generated by Django 6.0.7 on 2026-08-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', 'reservations_0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت پرداخت'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('wallet', 'کیف پول'), ('gateway', 'درگاه پرداخت'), ('temporary', 'رزرو موقت')], max_length=20, null=True, verbose_name='نوع پرداخت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
