# Generated by Django 6.1 on 2026-08-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ خروج'),
        ),
    ]
